github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true

tasks:
  - name: install & run
    env:
      NODE_OPTIONS: --openssl-legacy-provider
    init: |
      nvm install --lts
      nvm use --lts
      cd ..
      git clone https://github.com/module-federation/aegis-app
      cd aegis-app
      yarn
      yarn build
      cd ../aegis
      yarn
      yarn build
      yarn link
      cd ..
      git clone https://github.com/module-federation/aegis-host
      cd aegis-host
      yarn
      yarn link @module-federation/aegis
    command: |
      cd ../aegis-app
      nohup node repo.js 8000 dist &
      nohup node repo.js 8001 cache &
      cd ../aegis-host
      yarn build
      gp sync-done start
      node --title aegis src/bootstrap.js | tee public/aegis.log

  - name: mongodb
    command: |
      cd ../aegis
      ./mongo.sh

  - name: service mesh
    openMode: split-right
    env:
      PORT: 8888
      SWITCH: true
    command: |
      gp sync-await start
      cd ../aegis-host
      node --title webswitch src/bootstrap.js | tee public/webswitch.log

  - name: watch aegis-app
    command: |
      cd ../aegis-app
      yarn watch

  - name: watch aegis
    command: |
      cd ../aegis
      yarn watch

ports:
  - port: 8000
    description: local repo
    visibility: public
    onOpen: ignore
  - port: 8080
    description: http api
    visibility: public
    onOpen: open-preview
  - port: 8888
    description: webswitch
    visibility: public
    onOpen: open-browser
  - port: 27017
    description: mongodb
    visibility: public
    onOpen: ignore
  - port: 5353
    description: multicast dns
    visibility: public
    onOpen: ignore
